### ISSUE TITLE
FreehandRoi -- Error

### ISSUE THREAD

**Issue by behnazeslami** [webnamics/u-dicom-viewer#5]
Hi,
I want to use u-dicom-viewer, but I have a problem after uploading dicom image, FreehandRoi have got error which part of it is: 

1 of 2 errors on the page
TypeError: item.data.area is undefined
render
src/components/MeasureItem.js:109

  106 |     break          
  107 | case 'FreehandRoi':
  108 |     pText = <div>
> 109 |                 <div> A: {item.data.area.toFixed(2)} mm² </div>
      | ^  110 |                 <div> M: {item.data.meanStdDev.mean.toFixed(2)} {item.data.unit} </div>
  111 |         <       div> SD: {item.data.meanStdDev.stdDev.toFixed(2)} {item.data.unit} </div>
  112 |             </div>

Is it possible guide me to solve this issue?
Thanks

**Comment by webnamics** [comment]
I think this is an issue with CornerstoneTools, I found out that the data of measure become available after cornerstonetoolsmeasurementcompleted event, this information is not yet ready on event.

So I have implemented the following workaround, at least until I find a better solution.

In the file 'src/components/dicomviewer.js' at row 260 substitute the 'onMeasurementCompleted' function with this:

`    onMeasurementCompleted = (e) => {
      //console.log('cornerstonetoolsmeasurementcompleted: ', e.detail.measurementData)
      const measure = {
        tool: this.props.tool,
        note: '',
        data: e.detail.measurementData
      }
      if (this.props.tool === "FreehandRoi") {
        setTimeout(() => {
          this.measurementSave(measure)
          this.props.setActiveMeasurements(this.measurements)
        }, 500)
      } else {
        this.measurementSave(measure)
        this.props.setActiveMeasurements(this.measurements)
      }
    }`
	
Note the delay to save the measurement for freehand tool, to wait for the data to become available.

**Comment by behnazeslami** [comment]
Thanks.
It works 👍

**Comment by webnamics** [comment]
Correct in version 0.6.0
