### ISSUE TITLE
[Open DICOMDIR] in the Viewer, does not import and show Dicom images in  folder

### ISSUE THREAD

**Issue by behnazeslami** [webnamics/u-dicom-viewer#6]
Hi,
I want to upload a folder that contains some Dicom images. Unfortunately after uploading nothing happen without any images and just  the alert box with this message appears in the viewer:

> Upload 10 files to this site?
This will upload all files from "dicom_folder". Only do this if you trust the site.

After press uploads nothing import in the viewer for doing the rest of the process.

How can I solve this issue?
Thanks.

**Comment by webnamics** [comment]
In version 0.5.1 the command 'Open DICOMDIR' is used to open only a DICOMDIR file, i.e. the folder you select must contains a DICOMDIR file with associated dicom files. 

In version 0.6.0 was added the command 'Open Folder' to open multiple files from a local file system.
