### ISSUE TITLE
Suggestion for beginner

### ISSUE THREAD

**Issue by ncovgt2020** [webnamics/u-dicom-viewer#9]
Hi,

Thanks for sharing your amazing viewer. I would like to learn to build a viewer like yours. I have followed the examples in cornerstone and seen other implementations but, as a beginner, it is quite difficult to understand them to develop my own viewer. I was wondering if you could please suggest any beginner tutorials on learning cornerstone from zero or learning to create your specific dicom viewer. Thank you!

**Comment by webnamics** [comment]
I  have answered privately.

**Comment by ncovgt2020** [comment]
Thanks... but where exactly did you send the answer? I have nothing in my email and, as far as I know, [github has no private messaging](https://github.community/t5/How-to-use-Git-and-GitHub/How-to-sned-a-private-message-to-another-Git/m-p/33856).
